# Generated by Django 5.1.6 on 2025-05-02 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0022_cliente_contacto_cargo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestadosinmovimiento',
            name='actualizado_por_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoestado',
            name='actualizado_por_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
