# Generated by Django 5.1.6 on 2025-05-02 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_historialestadosinmovimiento_actualizado_por_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoCambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=500)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivos_cambio', to='clientes.cliente')),
                ('estado_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motivos_anteriores', to='clientes.estadoreporte')),
                ('estado_nuevo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motivos_nuevos', to='clientes.estadoreporte')),
            ],
        ),
    ]
